project:
  type: website
  
website:
  title: "Vinay Kumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - text: Project
        menu:
          - href: data_viz_final.html
            text: Data Visualization Final Project
          - href: Kumar_Final_Presentation.pptx
            text: Data Visualization Final PPT
          - href: Kumar data visualization paper.pdf
            text: Data Visualization Final Paper
          - href: Oparaji_Epps_6302_Final_Paper.pdf
            text: Data Collection Final Paper
          - href: Data Collection.pdf
            text: Data Collection Final PPT
      - href: coursework.qmd
        text: Coursework
      - text: Data Visualization
        menu: 
          - href: data_visualization.qmd
          - text: Data Visualization Assignment(1-4)
          - href: Assignment6.
            text: Assignment 6
          - href: Assignment7.
            text: Assignment 7
          - href: https://vinaykumar945.shinyapps.io/Assignment6/
            text: Assignment 6
      - href: data_collection.qmd
        text: Data Collection
      - href: vinaykumarcv.pdf
        text: CV
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
   
editor: visual
